title: Yifu Eve Ding 
logo: /img/photo.jpeg

description: Post-doc at MIT Energy Initiative | Ph.D. in Engineering Science, Oxford University.| Data-driven stochastic optimization | Clean and reliable energy systems &#128267| Science blogs & talks &#129299 
show_downloads: False
theme: jekyll-theme-minimal
include: ['Pages']

plugins:
  - jemoji
