title: Yifu Eve Ding
logo: /img/photo.jpeg

description: Post-doc at MIT Energy Initiative | Ph.D. in Engineering Science, Oxford University.| Data-driven stochastic optimization &#129409| Clean and reliable energy systems &#129409| Science blogs & talks 
show_downloads: False
theme: jekyll-theme-minimal
include: ['Pages']
