title: Yifu Eve Ding
logo: /img/photo.jpeg

description: Post-doc at MIT Energy Initiative | Ph.D. in Engineering Science, Oxford.| Data-driven stochastic optimization | Clean and reliable energy systems | Science blogs & talks 
show_downloads: False
theme: jekyll-theme-minimal
include: ['Pages']
