title: Yifu Eve Ding
logo: /img/photo.jpeg

description: Post-doc at MIT Energy Initiative | Ph.D. in Engineering Science, University of Oxford.| Data-driven and Learning-based optimization
show_downloads: False
theme: jekyll-theme-minimal
include: ['Pages']
