title: Yifu Eve Ding
logo: /img/photo.jpeg

description: I am a post-doc at MIT Energy Initiative. I completed my D.Phil. in Engineering Science, University of Oxford. My research interests include machine learning probabilistic forecasting, data-driven control and optimisation for energy systems considering uncertainty
show_downloads: False
theme: jekyll-theme-minimal
include: ['Pages']
