title: Yifu Eve Ding
logo: /img/photo.jpeg
github:
  is_project_page: False
description: I am a post-doctoal associate at MIT energy initiative. My research focus is xxxx. I obtained my PhD degree in Engineering Science from University of Oxford, and my master degree in Sustainable Energy Futures at Imperial College London 
show_downloads: False
theme: jekyll-theme-minimal
